[workspace]
resolver = "2"
members = ["day*"]

[workspace.dependencies]
nom = "7.1"
rayon = "1.10"
itertools = "0.13"
divan = "0.1"
grid = "0.15"
glam = "0.29"
nom_locate = "4.2"
pathfinding = "4.12"
rstest = "0.26"


